---
name: Test ontology

on:
  push:
    branches:
      - main
    paths:
      - '**.owl'
      - '**.rdf'
      - '**.ttl'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.owl'
      - '**.rdf'
      - '**.ttl'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    container: obolibrary/odklite
    steps:
      - uses: actions/checkout@v4

      - run: check-rdfxml gfo-light.ttl
      - run: check-rdfxml modules/gfo-base.owl

      - run: robot reason --input gfo-light.ttl
      - run: robot reason --input modules/gfo-base.owl

      - run: robot report --input gfo-light.ttl --profile qc_report/profile.txt
      - run: robot report --input modules/gfo-base.owl --profile qc_report/profile.txt
