---
name: Test ontology

on:
  push:
    branches:
      - main
    paths:
      - '**.owl'
      - '**.rdf'
      - '**.ttl'
  pull_request:
    branches:
      - main
    paths:
      - '**.owl'
      - '**.rdf'
      - '**.ttl'

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    container: obolibrary/odklite
    steps:
      - uses: actions/checkout@v4
      - run: check-rdfxml gfo.owl
